### PR TITLE
Automated Changelog Entry for 0.2.0 on main

### PR DESCRIPTION
**Pull request by DerThorsten**
Automated Changelog Entry for 0.2.0 on main

After merging this PR run the "Full Release" Workflow on your fork of `jupyter_releaser` with the following inputs
| Input  | Value |
| ------------- | ------------- |
| Target | jupyterlite/xeus-lua-kernel  |
| Branch  | main  |
| Version Spec | 0.2.0 |
| Since | v0.1.1 |

### CODE REVIEW

**Comment by jtpio** [comment]
@DerThorsten how did the release go?

It looks like the GitHub release is still a draft:

image

And PyPI still shows 0.1.1 as the latest:

image

Sounds like there could have been an issue with the tokens or publish step?

Happy to help look into it. Otherwise you might want to use the "Publish Release" workflow and paste the link to the draft GitHub release to resume:

image

**Comment by DerThorsten** [comment]
I was stopped by the "Full Release" workflow failing [here](https://github.com/DerThorsten/jupyter_releaser/runs/4249770104?check_suite_focus=true#step:4:125) with: 
```
COMMAND: npm version --git-tag-version false 0.2.0
npm ERR! Version not changed, might want --allow-same-version
```

**Comment by jtpio** [comment]
@DerThorsten which parameters did you use as the inputs?

I just run the "Publish Release" to resume where it stopped and everything went through: https://github.com/jtpio/jupyter_releaser/runs/4258032458?check_suite_focus=true

**Comment by DerThorsten** [comment]
@jtpio I used 
```
Target | jupyterlite/xeus-lua-kernel
Branch | main
Version Spec | 0.2.0
```

**Pull request merged**
